# Generated by Django 5.2.5 on 2025-09-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_director_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.director'),
        ),
    ]
