# Generated by Django 5.2.5 on 2025-12-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_movie_screenwriter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
