# Generated by Django 5.2.5 on 2026-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_end_date_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='movies.director'),
        ),
        migrations.AddField(
            model_name='episode',
            name='guest_stars',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='episode',
            name='screenwriters',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='movies.screenwriter'),
        ),
    ]
