# Generated by Django 5.2.5 on 2026-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_episode_directors_episode_guest_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='season',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='movies.director'),
        ),
        migrations.AddField(
            model_name='season',
            name='screenwriters',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='movies.screenwriter'),
        ),
    ]
