# Generated by Django 5.2.5 on 2026-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_season_actors_season_directors_season_screenwriters'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='season_posters/'),
        ),
    ]
