# Generated by Django 5.2.5 on 2026-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_season_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
    ]
