# Generated by Django 5.2.5 on 2026-02-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_actor_birth_date_actor_birth_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='director',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='screenwriter',
            name='bio',
        ),
    ]
